// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdataDemo.Data.Entities;

#nullable disable

namespace OdataDemo.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250217122455_sa")]
    partial class sa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OdataDemo.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Cars"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Motorbikes"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Electronics"
                        });
                });

            modelBuilder.Entity("OdataDemo.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "VinFast",
                            CategoryId = 1,
                            Cost = 1900m,
                            ImageName = "VF9.jpg",
                            ProductName = "VinFast President",
                            Type = "Car"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Tesla",
                            CategoryId = 1,
                            Cost = 13000m,
                            ImageName = "ModelS.jpg",
                            ProductName = "Tesla Model S",
                            Type = "Car"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            CategoryId = 1,
                            Cost = 34999m,
                            ImageName = "X7.jpg",
                            ProductName = "BMW X7",
                            Type = "Car"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Mercedes-Benz",
                            CategoryId = 1,
                            Cost = 21000m,
                            ImageName = "GClass.jpg",
                            ProductName = "Mercedes-Benz G-Class",
                            Type = "Car"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Ford",
                            CategoryId = 1,
                            Cost = 11000m,
                            ImageName = "Mustang.jpg",
                            ProductName = "Ford Mustang",
                            Type = "Car"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Honda",
                            CategoryId = 2,
                            Cost = 16000m,
                            ImageName = "CBR1000RR.jpg",
                            ProductName = "Honda CBR1000RR",
                            Type = "Motorbike"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Yamaha",
                            CategoryId = 2,
                            Cost = 17000m,
                            ImageName = "R1.jpg",
                            ProductName = "Yamaha R1",
                            Type = "Motorbike"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Apple",
                            CategoryId = 3,
                            Cost = 2500m,
                            ImageName = "MacBookPro.jpg",
                            ProductName = "MacBook Pro 16",
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Cost = 1200m,
                            ImageName = "GalaxyS23.jpg",
                            ProductName = "Samsung Galaxy S23 Ultra",
                            Type = "Smartphone"
                        });
                });

            modelBuilder.Entity("OdataDemo.Data.Entities.Product", b =>
                {
                    b.HasOne("OdataDemo.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OdataDemo.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
